name: workout_manager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.0
  equatable: ^1.2.0
  
  freezed_annotation: ^0.11.0
  flutter_bloc: ^4.0.1
  google_sign_in: ^4.4.4
  firebase_auth: ^0.16.0
  flushbar: ^1.10.0
  
  auto_route: ^0.4.5
  get_it: ^4.0.2
  injectable: ^0.3.0
  firestore_helpers: ^3.2.1+1
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  uuid: ^2.0.4
  kt_dart: ^0.7.0+1
  async: ^2.4.1
  rxdart: ^0.24.1
  observable: ^0.22.2
  progress_indicators: ^0.1.5
  table_calendar: ^2.2.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.11.2
  
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
  auto_route_generator: ^0.4.8
  injectable_generator: ^0.3.5
  build_runner: ^1.10.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/parties/none.jpg
      - assets/parties/chest.jpg
      - assets/parties/legs.jpg
      - assets/parties/abs.jpg
      - assets/parties/shoulders.jpg
      - assets/parties/glutes.jpg
      - assets/parties/back.jpg
      - assets/parties/biceps.jpg
      - assets/parties/triceps.jpg
      
      - assets/util/primary.jpg
      - assets/util/secondary.jpg
      - assets/util/empty_img.jpg
      
      #ICONS FROM "https://icons8.com/icons/set/bench-over-head", "https://icons8.com/icons/set/bench-press" Bench Press and other icons by  "https://icons8.com" 
      - assets/workout/dumbbell.png
      - assets/workout/barbell.png
      - assets/workout/bench_press.png
      - assets/workout/bent_dumbbell.png
      - assets/workout/boxing.png
      - assets/workout/curls.png
      - assets/workout/curve_bench.png
      - assets/workout/cycling.png
      - assets/workout/jumping_rod.png
      - assets/workout/pullups.png
      - assets/workout/pushups.png
      - assets/workout/rowing_machine.png
      - assets/workout/running.png
      - assets/workout/squats.png
      - assets/workout/stairs.png
      - assets/workout/stepper.png
      - assets/workout/treadmill.png
  fonts: 
    - family: ArchivoNarrow
      fonts:
        - asset: fonts/ArchivoNarrow-Bold.ttf
        - asset: fonts/ArchivoNarrow-Regular.ttf
        - asset: fonts/ArchivoNarrow-Medium.ttf
        - asset: fonts/ArchivoNarrow-SemiBold.ttf
        
    - family: Signika
      fonts:
        - asset: fonts/Signika-Bold.ttf
        - asset: fonts/Signika-Regular.ttf
        - asset: fonts/Signika-Light.ttf
        - asset: fonts/Signika-SemiBold.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
